/**
 * Quarkus CIS Home service
 * Quarkus ChristInformationSystem
 *
 * The version of the OpenAPI document: 1.0
 * Contact: dominik@christ-rlp.de
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { CisRoles } from './cisRoles';
import { CisUserGroup } from './cisUserGroup';
import { CisGroup } from './cisGroup';


export interface CisSystemUser { 
    id?: string;
    firstName?: string;
    lastName?: string;
    cisGroup?: CisGroup;
    roles?: CisRoles;
    group?: CisUserGroup;
    email?: string;
    name?: string;
    userName?: string;
}

