/**
 * Quarkus CIS Home service
 * Quarkus ChristInformationSystem
 *
 * The version of the OpenAPI document: 1.0
 * Contact: dominik@christ-rlp.de
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { PaymentOption } from './paymentOption';


export interface ContractAggregateResponse { 
    name?: string;
    contractNumber?: string;
    customerNumber?: string;
    amount?: number;
    yearlyAmount?: number;
    paymentOption?: PaymentOption;
    firstPayment?: string;
    lastPayment?: string;
    nextPayment?: string;
}

