/**
 * Quarkus CIS Home service
 * Quarkus ChristInformationSystem
 *
 * The version of the OpenAPI document: 1.0
 * Contact: dominik@christ-rlp.de
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { MeetingNoteDescription } from './meetingNoteDescription';
import { ParticipantJpaEntity } from './participantJpaEntity';


export interface LastNotesJpaEntity { 
    id?: string;
    meeting?: string;
    session?: string;
    note?: string;
    participantId?: string;
    created?: string;
    participant?: ParticipantJpaEntity;
    noteDescription?: MeetingNoteDescription;
    dayString?: string;
}

