/**
 * Quarkus CIS Home service
 * Quarkus ChristInformationSystem
 *
 * The version of the OpenAPI document: 1.0
 * Contact: dominik@christ-rlp.de
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export type MeetingStatus = 'ACTIVE' | 'PAUSED' | 'CANCELED' | 'FINISHED';

export const MeetingStatus = {
    Active: 'ACTIVE' as MeetingStatus,
    Paused: 'PAUSED' as MeetingStatus,
    Canceled: 'CANCELED' as MeetingStatus,
    Finished: 'FINISHED' as MeetingStatus
};

