/**
 * Quarkus CIS Home service
 * Quarkus ChristInformationSystem
 *
 * The version of the OpenAPI document: 1.0
 * Contact: dominik@christ-rlp.de
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { TodoResponse } from './todoResponse';


export interface MultiTodoResponse { 
    list?: Array<TodoResponse>;
    inCategories?: { [key: string]: Array<string>; };
    categories?: Set<string>;
    overdue?: Set<string>;
}

