/**
 * Quarkus CIS Home service
 * Quarkus ChristInformationSystem
 *
 * The version of the OpenAPI document: 1.0
 * Contact: dominik@christ-rlp.de
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export type PaymentOption = 'UNKNOWN' | 'YEAR' | 'QUARTER' | 'MONTH';

export const PaymentOption = {
    Unknown: 'UNKNOWN' as PaymentOption,
    Year: 'YEAR' as PaymentOption,
    Quarter: 'QUARTER' as PaymentOption,
    Month: 'MONTH' as PaymentOption
};

