/**
 * Quarkus CIS Home service
 * Quarkus ChristInformationSystem
 *
 * The version of the OpenAPI document: 1.0
 * Contact: dominik@christ-rlp.de
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { ShoppingListItemResponse } from './shoppingListItemResponse';


export interface ShoppingListResponse { 
    id?: string;
    name?: string;
    list?: Array<ShoppingListItemResponse>;
    storeGroupedList?: { [key: string]: Array<ShoppingListItemResponse>; };
    stores?: Set<string>;
}

