/**
 * Quarkus CIS Home service
 * Quarkus ChristInformationSystem
 *
 * The version of the OpenAPI document: 1.0
 * Contact: dominik@christ-rlp.de
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { QuickFilter } from './quickFilter';


export interface TodoResponse { 
    id?: string;
    title?: string;
    description?: string;
    category?: string;
    due?: string;
    important?: boolean;
    created?: string;
    overdue?: boolean;
    daysUntil?: number;
    filter?: QuickFilter;
}

