export * from './awsS3Resource.service';
import { AwsS3ResourceService } from './awsS3Resource.service';
export * from './exampleResource.service';
import { ExampleResourceService } from './exampleResource.service';
export * from './generalDriveWebAdapter.service';
import { GeneralDriveWebAdapterService } from './generalDriveWebAdapter.service';
export * from './keyGenWebAdapter.service';
import { KeyGenWebAdapterService } from './keyGenWebAdapter.service';
export * from './listCommandController.service';
import { ListCommandControllerService } from './listCommandController.service';
export * from './listCommandControllerV2.service';
import { ListCommandControllerV2Service } from './listCommandControllerV2.service';
export * from './lists.service';
import { ListsService } from './lists.service';
export * from './listsShoppingSettlement.service';
import { ListsShoppingSettlementService } from './listsShoppingSettlement.service';
export * from './listsTodo.service';
import { ListsTodoService } from './listsTodo.service';
export * from './meeting.service';
import { MeetingService } from './meeting.service';
export * from './participant.service';
import { ParticipantService } from './participant.service';
export * from './profile.service';
import { ProfileService } from './profile.service';
export * from './rabbitMqPublisher.service';
import { RabbitMqPublisherService } from './rabbitMqPublisher.service';
export * from './safe.service';
import { SafeService } from './safe.service';
export * from './school.service';
import { SchoolService } from './school.service';
export * from './sessionActivationController.service';
import { SessionActivationControllerService } from './sessionActivationController.service';
export * from './sessionTimeTrackCommandController.service';
import { SessionTimeTrackCommandControllerService } from './sessionTimeTrackCommandController.service';
export * from './sessionTimeTrackQueryController.service';
import { SessionTimeTrackQueryControllerService } from './sessionTimeTrackQueryController.service';
export * from './shopping.service';
import { ShoppingService } from './shopping.service';
export * from './shoppingListQueryResource.service';
import { ShoppingListQueryResourceService } from './shoppingListQueryResource.service';
export * from './shoppingStoreCommandResource.service';
import { ShoppingStoreCommandResourceService } from './shoppingStoreCommandResource.service';
export * from './tasksController.service';
import { TasksControllerService } from './tasksController.service';
export * from './teamController.service';
import { TeamControllerService } from './teamController.service';
export * from './wdysMeeting.service';
import { WdysMeetingService } from './wdysMeeting.service';
export * from './wdysMeetingNotes.service';
import { WdysMeetingNotesService } from './wdysMeetingNotes.service';
export * from './wdysTodo.service';
import { WdysTodoService } from './wdysTodo.service';
export * from './weekplanController.service';
import { WeekplanControllerService } from './weekplanController.service';
export const APIS = [AwsS3ResourceService, ExampleResourceService, GeneralDriveWebAdapterService, KeyGenWebAdapterService, ListCommandControllerService, ListCommandControllerV2Service, ListsService, ListsShoppingSettlementService, ListsTodoService, MeetingService, ParticipantService, ProfileService, RabbitMqPublisherService, SafeService, SchoolService, SessionActivationControllerService, SessionTimeTrackCommandControllerService, SessionTimeTrackQueryControllerService, ShoppingService, ShoppingListQueryResourceService, ShoppingStoreCommandResourceService, TasksControllerService, TeamControllerService, WdysMeetingService, WdysMeetingNotesService, WdysTodoService, WeekplanControllerService];
