export * from './accountResource.service';
import { AccountResourceService } from './accountResource.service';
export * from './drive.service';
import { DriveService } from './drive.service';
export * from './householdContracts.service';
import { HouseholdContractsService } from './householdContracts.service';
export * from './keyGenWebAdapter.service';
import { KeyGenWebAdapterService } from './keyGenWebAdapter.service';
export * from './listCommon.service';
import { ListCommonService } from './listCommon.service';
export * from './listShopping.service';
import { ListShoppingService } from './listShopping.service';
export * from './listShoppingSettlement.service';
import { ListShoppingSettlementService } from './listShoppingSettlement.service';
export * from './listShoppingStore.service';
import { ListShoppingStoreService } from './listShoppingStore.service';
export * from './listTodo.service';
import { ListTodoService } from './listTodo.service';
export * from './profile.service';
import { ProfileService } from './profile.service';
export * from './safe.service';
import { SafeService } from './safe.service';
export * from './school.service';
import { SchoolService } from './school.service';
export * from './shoppingListQueryResource.service';
import { ShoppingListQueryResourceService } from './shoppingListQueryResource.service';
export * from './wdysCollaboration.service';
import { WdysCollaborationService } from './wdysCollaboration.service';
export * from './wdysDashboard.service';
import { WdysDashboardService } from './wdysDashboard.service';
export * from './wdysMeeting.service';
import { WdysMeetingService } from './wdysMeeting.service';
export * from './wdysMeetingsessionQuery.service';
import { WdysMeetingsessionQueryService } from './wdysMeetingsessionQuery.service';
export * from './wdysNotes.service';
import { WdysNotesService } from './wdysNotes.service';
export * from './wdysParticipant.service';
import { WdysParticipantService } from './wdysParticipant.service';
export * from './wdysSession.service';
import { WdysSessionService } from './wdysSession.service';
export * from './wdysTimebooking.service';
import { WdysTimebookingService } from './wdysTimebooking.service';
export * from './wdysTodo.service';
import { WdysTodoService } from './wdysTodo.service';
export * from './weekplanPlan.service';
import { WeekplanPlanService } from './weekplanPlan.service';
export * from './weekplanTasks.service';
import { WeekplanTasksService } from './weekplanTasks.service';
export * from './weekplanTeam.service';
import { WeekplanTeamService } from './weekplanTeam.service';
export const APIS = [AccountResourceService, DriveService, HouseholdContractsService, KeyGenWebAdapterService, ListCommonService, ListShoppingService, ListShoppingSettlementService, ListShoppingStoreService, ListTodoService, ProfileService, SafeService, SchoolService, ShoppingListQueryResourceService, WdysCollaborationService, WdysDashboardService, WdysMeetingService, WdysMeetingsessionQueryService, WdysNotesService, WdysParticipantService, WdysSessionService, WdysTimebookingService, WdysTodoService, WeekplanPlanService, WeekplanTasksService, WeekplanTeamService];
